# Student Attendance 

---
**Problem Statement**
- EDU University wants to find out, whether class attendance by the students should be made compulsory.  
- For that, they gave you a dataset, SECTION1.csv  which includes the following attributes in the same order.

["Sno", "Department", "Branch", "Semester", "Course", "RegistrationNo", "StudentName", "Date", "Slot group", "Time", "ClassConducted", "ClassAttended"].

---

**Tasks**
- But after looking into the data, you reached to a conclusion that it is not in a proper format for analysing.  
- You need to manipulate the data and create a dataframe with the following attributes:
    - [RegistrationNo, Name, Date1, Date2, Date3, …. DateN]
- Each row corresponds to the data of a student. 
- The column names of Date1, Date2, Date3.... DateN should be replaced with the unique dates from the dataset.
- Values under Date1, Date2 … columns should be the total number of classes attended by the student on that date.

---

**Input Format**
1. The first file to read will be SECTION1.csv, which contains the data as mentioned above. This file is in .csv format and is present at the location (/data/training/SECTION1.csv)
2. The second file to read will be testcase.txt present at the location (/data/training/testcase.txt) which contains the following data:
    - First line represents the number of testcase pairs.
    - Followed by a set of RegistrationNo and date pairs. Each element of a pair is on a separate line.

**Output Format**
- For each pair in the testcase.txt, create an output file, outputn.txt  where n represents the pair number.
- outputn.txt should be present at the location (/code/outputn.txt) . 
- This file should include RegistrationNo and the attendance value on that particular date.

---

**Sample Test Cases**
- Sample Input
    - e.g. testcase.txt contains the following data:
        >- 3
        >- 16fcs201114
        >- 08/12/18
        >- 16fcs201112
        >- 09/11/18
        >- 16fcs201140
        >- 18/12/18

- Sample Output
    - output1.txt contains the following data:
        >- 16fcs201114
        >- 4
    - output2.txt contains the following data:
        >- 16fcs201112
        >- 2
    - output3.txt contains the following data:
        >- 16fcs201140
        >- 5

- Explanation
    - Student with Registration Number '16fcs201114' has attended 4 classes on '08/12/18'
    - Student with Registration Number '16fcs201112' has attended 2 classes on '09/11/18'
    - Student with Registration Number '16fcs201140' has attended 5 classes on '18/12/18'

In [ ]:
import pandas as pd
import numpy as np
import pandas as pd
from datetime import datetime

In [ ]:
# Read CSV file
data = pd.read_csv("/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-attendanceT/SECTION1.csv")

In [ ]:
# Assign column labels
data.columns = ["Sno", "Department", " Department ", "Semester", "Course", "RegistrationNo", 
                   "StudentName", "Date", "Slot group", "Time", "ClassConducted", "ClassAttended"]

In [ ]:
# Use loc function to select only required columns
data.loc[: , ['RegistrationNo', 'StudentName', 'Date', 'ClassAttended']]

In [ ]:
# Use groupby function to group together all the redundant values
table = data.groupby(['StudentName', 'RegistrationNo', 'Date']).agg({'ClassAttended': 'sum'})

# csvdf.pivot_table(csvdf,index=['RegistrationNo', 'StudentName', 'Date', 'ClassAttended'])
table1 = table.pivot_table(index = 'RegistrationNo', columns = 'Date', values = 'ClassAttended')
table1.fillna(0, inplace=True)
print(table1)

In [11]:
lst=[]
file = open('/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-attendanceT/testcase.txt', "r")
lst = file.read().splitlines()
L = len(lst)
T = int(lst[0])
i = 1

for j in range (0, T):
    res = ""
    reg = lst[i]
    dt = lst[i + 1]
    output = int(table1.loc[reg, dt])
    res = reg + "\n" + str(output)
    print(res)
    file2 = open('/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-attendanceT/output' + str(j + 1) + ".txt", "w")
    file2.write(str(res))
    file2.close()
    i += 2

Date            02/04/2019  08/03/2019  12/02/2019  12/03/2019  15/02/2019  \
RegistrationNo
16SCSE101002           2.0         2.0         2.0         2.0         2.0
16SCSE101005           2.0         2.0         0.0         2.0         2.0
16SCSE101012           2.0         2.0         0.0         2.0         0.0
16SCSE101015           2.0         2.0         2.0         2.0         2.0
16SCSE101019           0.0         0.0         0.0         0.0         0.0
16SCSE101028           0.0         0.0         0.0         0.0         0.0
16SCSE101029           2.0         2.0         0.0         2.0         0.0
16SCSE101052           2.0         2.0         2.0         2.0         2.0
16SCSE101057           0.0         0.0         0.0         2.0         0.0
16SCSE101060           2.0         2.0         0.0         2.0         0.0
16SCSE101071           2.0         2.0         2.0         2.0         2.0
16SCSE101072           2.0         2.0         2.0         2.0         2.0
16SCSE101085           0.0         0.0         0.0         0.0         0.0
16SCSE101095           0.0         2.0         0.0         0.0         0.0
16SCSE101107           2.0         2.0         0.0         2.0         0.0
16SCSE101111           0.0         0.0         0.0         2.0         0.0
16SCSE101127           0.0         2.0         2.0         0.0         0.0
16SCSE101141           2.0         0.0         0.0         2.0         0.0
16SCSE101158           2.0         2.0         0.0         0.0         0.0
16SCSE101160           2.0         2.0         2.0         2.0         2.0
16SCSE101167           2.0         0.0         0.0         0.0         0.0
16SCSE101171           0.0         0.0         2.0         0.0         0.0
16SCSE101188           2.0         2.0         0.0         2.0         0.0
16SCSE101191           0.0         2.0         0.0         2.0         0.0
16SCSE101195           0.0         2.0         2.0         2.0         2.0
16SCSE101215           0.0         0.0         0.0         2.0         0.0
16SCSE101220           2.0         2.0         0.0         2.0         0.0
16SCSE101222           2.0         0.0         0.0         2.0         0.0
16SCSE101232           2.0         2.0         0.0         2.0         0.0
16SCSE101241           2.0         2.0         0.0         2.0         0.0
...                    ...         ...         ...         ...         ...
16SCSE101318           2.0         2.0         0.0         2.0         0.0
16SCSE101322           0.0         0.0         0.0         0.0         0.0
16SCSE101323           0.0         2.0         0.0         0.0         0.0
16SCSE101350           2.0         2.0         2.0         2.0         2.0
16SCSE101383           0.0         0.0         0.0         0.0         0.0
16SCSE101391           0.0         0.0         0.0         0.0         0.0
16SCSE101415           2.0         2.0         0.0         2.0         0.0
16SCSE101433           0.0         0.0         0.0         0.0         0.0
16SCSE101463           0.0         0.0         2.0         0.0         0.0
16SCSE101489           2.0         2.0         0.0         2.0         0.0
16SCSE101497           0.0         0.0         0.0         0.0         0.0
16SCSE101506           0.0         2.0         0.0         0.0         0.0
16SCSE101520           2.0         0.0         0.0         2.0         0.0
16SCSE101529           2.0         0.0         0.0         2.0         0.0
16SCSE101547           0.0         2.0         2.0         0.0         0.0
16SCSE101580           2.0         0.0         0.0         2.0         0.0
16SCSE101601           0.0         0.0         0.0         0.0         0.0
16SCSE101617           0.0         0.0         0.0         0.0         0.0
16SCSE101662           2.0         2.0         0.0         2.0         0.0
16SCSE101666           2.0         2.0         0.0         0.0         0.0
16SCSE101713           0.0         0.0         0.0         2.0         0.0
16SCSE101714           2.0         2.0         2.0         2.0         2.0
16SCSE101728           2.0         2.0         2.0         2.0         0.0
16SCSE101737           2.0         0.0         0.0         2.0         0.0
16SCSE101739           0.0         0.0         0.0         0.0         0.0
16SCSE101757           2.0         0.0         0.0         2.0         0.0
16SCSE101798           2.0         2.0         2.0         2.0         2.0
16SCSE101889           0.0         0.0         0.0         0.0         0.0
16SCSE102013           0.0         2.0         2.0         2.0         0.0
16SCSE102014           2.0         2.0         2.0         2.0         0.0

Date            15/03/2019  22/03/2019  26/02/2019  26/03/2019  29/01/2019  \
RegistrationNo
16SCSE101002           1.0         0.0         0.0         2.0         0.0
16SCSE101005           0.0         0.0         0.0         2.0         0.0
16SCSE101012           2.0         0.0         2.0         2.0         0.0
16SCSE101015           0.0         0.0         0.0         2.0         0.0
16SCSE101019           0.0         0.0         0.0         0.0         0.0
16SCSE101028           0.0         0.0         0.0         0.0         0.0
16SCSE101029           2.0         0.0         2.0         2.0         0.0
16SCSE101052           2.0         0.0         0.0         0.0         0.0
16SCSE101057           0.0         0.0         0.0         2.0         2.0
16SCSE101060           0.0         0.0         0.0         0.0         0.0
16SCSE101071           2.0         0.0         0.0         2.0         0.0
16SCSE101072           2.0         0.0         0.0         2.0         0.0
16SCSE101085           0.0         0.0         0.0         0.0         2.0
16SCSE101095           2.0         2.0         2.0         2.0         0.0
16SCSE101107           2.0         2.0         2.0         2.0         0.0
16SCSE101111           2.0         0.0         0.0         0.0         0.0
16SCSE101127           2.0         2.0         0.0         2.0         0.0
16SCSE101141           2.0         0.0         0.0         2.0         0.0
16SCSE101158           0.0         0.0         0.0         0.0         2.0
16SCSE101160           0.0         2.0         0.0         2.0         0.0
16SCSE101167           0.0         0.0         2.0         0.0         0.0
16SCSE101171           0.0         0.0         0.0         0.0         0.0
16SCSE101188           2.0         0.0         2.0         2.0         0.0
16SCSE101191           2.0         2.0         2.0         2.0         0.0
16SCSE101195           2.0         0.0         0.0         2.0         0.0
16SCSE101215           2.0         0.0         0.0         0.0         0.0
16SCSE101220           2.0         0.0         2.0         2.0         0.0
16SCSE101222           2.0         2.0         2.0         2.0         0.0
16SCSE101232           2.0         2.0         2.0         2.0         0.0
16SCSE101241           2.0         0.0         0.0         0.0         0.0
...                    ...         ...         ...         ...         ...
16SCSE101318           2.0         2.0         2.0         2.0         0.0
16SCSE101322           0.0         0.0         0.0         0.0         4.0
16SCSE101323           2.0         2.0         2.0         2.0         0.0
16SCSE101350           0.0         0.0         0.0         0.0         0.0
16SCSE101383           0.0         0.0         0.0         0.0         0.0
16SCSE101391           0.0         0.0         0.0         0.0         0.0
16SCSE101415           2.0         0.0         2.0         2.0         0.0
16SCSE101433           0.0         0.0         0.0         0.0         0.0
16SCSE101463           0.0         0.0         0.0         0.0         0.0
16SCSE101489           2.0         0.0         2.0         2.0         2.0
16SCSE101497           0.0         0.0         0.0         0.0         0.0
16SCSE101506           2.0         0.0         2.0         2.0         0.0
16SCSE101520           2.0         0.0         2.0         2.0         0.0
16SCSE101529           2.0         2.0         2.0         2.0         0.0
16SCSE101547           2.0         2.0         0.0         2.0         0.0
16SCSE101580           2.0         0.0         0.0         2.0         0.0
16SCSE101601           0.0         0.0         2.0         0.0         0.0
16SCSE101617           0.0         0.0         0.0         0.0         0.0
16SCSE101662           2.0         0.0         2.0         2.0         0.0
16SCSE101666           2.0         0.0         2.0         2.0         0.0
16SCSE101713           2.0         0.0         0.0         2.0         0.0
16SCSE101714           2.0         0.0         0.0         2.0         0.0
16SCSE101728           2.0         0.0         0.0         2.0         0.0
16SCSE101737           2.0         0.0         0.0         2.0         4.0
16SCSE101739           0.0         0.0         0.0         0.0         0.0
16SCSE101757           2.0         0.0         2.0         2.0         0.0
16SCSE101798           2.0         0.0         0.0         2.0         0.0
16SCSE101889           0.0         0.0         0.0         0.0         0.0
16SCSE102013           2.0         0.0         0.0         2.0         0.0
16SCSE102014           2.0         0.0         0.0         0.0         0.0

Date            29/03/2019
RegistrationNo
16SCSE101002           2.0
16SCSE101005           2.0
16SCSE101012           2.0
16SCSE101015           2.0
16SCSE101019           0.0
16SCSE101028           0.0
16SCSE101029           2.0
16SCSE101052           0.0
16SCSE101057           2.0
16SCSE101060           2.0
16SCSE101071           2.0
16SCSE101072           2.0
16SCSE101085           0.0
16SCSE101095           2.0
16SCSE101107           2.0
16SCSE101111           0.0
16SCSE101127           2.0
16SCSE101141           2.0
16SCSE101158           2.0
16SCSE101160           2.0
16SCSE101167           0.0
16SCSE101171           0.0
16SCSE101188           2.0
16SCSE101191           2.0
16SCSE101195           2.0
16SCSE101215           0.0
16SCSE101220           2.0
16SCSE101222           2.0
16SCSE101232           2.0
16SCSE101241           2.0
...                    ...
16SCSE101318           2.0
16SCSE101322           0.0
16SCSE101323           2.0
16SCSE101350           0.0
16SCSE101383           0.0
16SCSE101391           0.0
16SCSE101415           2.0
16SCSE101433           0.0
16SCSE101463           0.0
16SCSE101489           2.0
16SCSE101497           0.0
16SCSE101506           2.0
16SCSE101520           2.0
16SCSE101529           2.0
16SCSE101547           2.0
16SCSE101580           2.0
16SCSE101601           0.0
16SCSE101617           0.0
16SCSE101662           2.0
16SCSE101666           2.0
16SCSE101713           2.0
16SCSE101714           2.0
16SCSE101728           2.0
16SCSE101737           2.0
16SCSE101739           0.0
16SCSE101757           2.0
16SCSE101798           2.0
16SCSE101889           0.0
16SCSE102013           2.0
16SCSE102014           2.0

[64 rows x 11 columns]
16SCSE102014
2
16SCSE101350
0

In [45]:
# Number of unique values in a DataFrame
csvdata.nunique(axis=0, dropna=True)

Sno               1119
Department           1
 Department          2
Semester             1
Course               1
RegistrationNo      64
StudentName         64
Date                11
Slot group         785
Time                 4
ClassConducted       1
ClassAttended        3
dtype: int64

In [7]:
# Finding unique values
csvdf.Date.unique()

array(['12/03/2019', '08/03/2019', '15/03/2019', '22/03/2019',
       '26/03/2019', '12/02/2019', '15/02/2019', '29/03/2019',
       '02/04/2019', '29/01/2019', '26/02/2019'], dtype=object)

In [11]:
csvdf = np.array(['12/03/2019', '08/03/2019', '15/03/2019', '22/03/2019',
       '26/03/2019', '12/02/2019', '15/02/2019', '29/03/2019',
       '02/04/2019', '29/01/2019', '26/02/2019']) 
  
# Converting to series 
s = pd.Series(csvdf) 
print(s)

0     12/03/2019
1     08/03/2019
2     15/03/2019
3     22/03/2019
4     26/03/2019
5     12/02/2019
6     15/02/2019
7     29/03/2019
8     02/04/2019
9     29/01/2019
10    26/02/2019
dtype: object

In [4]:
rpath = '/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-attendanceT/SECTION1.csv'
spath = '/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-attendanceT/sample1.csv'

org_df = pd.read_csv(rpath)

to_drop = ['5', '2', 'EMPS3012', 'School of Computing Science & Engineering',
           'B.Tech/B.Tech (Hons) Computer Science Engineering',
           '2G-L48-2G-2G-L48-L48', 'Sem VI', '04:00-04:50']

df = org_df.drop(to_drop, axis=1)

df.columns = ['RegistrationNo', 'StudentName', 'Date', 'ClassAttend']
print(df)


u_regno = '16SCSE102014'     #pull out from testcase.txt
u2_date = '26/03/2019'          #pull out from testcase.txt

disp_reg = df[['Date','ClassAttend']][(df.RegistrationNo == u_regno)]
print(disp_reg)

     RegistrationNo       StudentName        Date  ClassAttend
0      16SCSE101002  NISHCHHAL SHARMA  12/03/2019            1
1      16SCSE101002  NISHCHHAL SHARMA  08/03/2019            1
2      16SCSE101002  NISHCHHAL SHARMA  12/03/2019            1
3      16SCSE101002  NISHCHHAL SHARMA  15/03/2019            1
4      16SCSE101002  NISHCHHAL SHARMA  08/03/2019            1
5      16SCSE101002  NISHCHHAL SHARMA  22/03/2019            0
6      16SCSE101002  NISHCHHAL SHARMA  22/03/2019            0
7      16SCSE101002  NISHCHHAL SHARMA  26/03/2019            1
8      16SCSE101002  NISHCHHAL SHARMA  26/03/2019            1
9      16SCSE101002  NISHCHHAL SHARMA  12/02/2019            1
10     16SCSE101002  NISHCHHAL SHARMA  12/02/2019            1
11     16SCSE101002  NISHCHHAL SHARMA  15/02/2019            1
12     16SCSE101002  NISHCHHAL SHARMA  15/02/2019            1
13     16SCSE101002  NISHCHHAL SHARMA  29/03/2019            1
14     16SCSE101002  NISHCHHAL SHARMA  29/03/2019            1
15     16SCSE101002  NISHCHHAL SHARMA  02/04/2019            1
16     16SCSE101002  NISHCHHAL SHARMA  02/04/2019            1
17     16SCSE101005      NAMAN KAPOOR  15/02/2019            1
18     16SCSE101005      NAMAN KAPOOR  12/02/2019            0
19     16SCSE101005      NAMAN KAPOOR  15/02/2019            1
20     16SCSE101005      NAMAN KAPOOR  29/03/2019            1
21     16SCSE101005      NAMAN KAPOOR  12/02/2019            0
22     16SCSE101005      NAMAN KAPOOR  29/03/2019            1
23     16SCSE101005      NAMAN KAPOOR  02/04/2019            1
24     16SCSE101005      NAMAN KAPOOR  02/04/2019            1
25     16SCSE101005      NAMAN KAPOOR  12/03/2019            1
26     16SCSE101005      NAMAN KAPOOR  12/03/2019            1
27     16SCSE101005      NAMAN KAPOOR  15/03/2019            0
28     16SCSE101005      NAMAN KAPOOR  15/03/2019            0
29     16SCSE101005      NAMAN KAPOOR  26/03/2019            1
...             ...               ...         ...          ...
1089   16SCSE102013    SHIVAM DHINGRA  26/03/2019            1
1090   16SCSE102013    SHIVAM DHINGRA  29/03/2019            1
1091   16SCSE102013    SHIVAM DHINGRA  29/03/2019            1
1092   16SCSE102013    SHIVAM DHINGRA  26/03/2019            1
1093   16SCSE102013    SHIVAM DHINGRA  15/02/2019            0
1094   16SCSE102013    SHIVAM DHINGRA  15/02/2019            0
1095   16SCSE102013    SHIVAM DHINGRA  12/03/2019            1
1096   16SCSE102013    SHIVAM DHINGRA  12/03/2019            1
1097   16SCSE102013    SHIVAM DHINGRA  08/03/2019            1
1098   16SCSE102013    SHIVAM DHINGRA  08/03/2019            1
1099   16SCSE102013    SHIVAM DHINGRA  12/02/2019            1
1100   16SCSE102013    SHIVAM DHINGRA  12/02/2019            1
1101   16SCSE102014      MANALI ANAND  15/02/2019            0
1102   16SCSE102014      MANALI ANAND  15/02/2019            0
1103   16SCSE102014      MANALI ANAND  12/02/2019            1
1104   16SCSE102014      MANALI ANAND  12/02/2019            1
1105   16SCSE102014      MANALI ANAND  12/03/2019            1
1106   16SCSE102014      MANALI ANAND  02/04/2019            1
1107   16SCSE102014      MANALI ANAND  12/03/2019            1
1108   16SCSE102014      MANALI ANAND  02/04/2019            1
1109   16SCSE102014      MANALI ANAND  15/03/2019            1
1110   16SCSE102014      MANALI ANAND  15/03/2019            1
1111   16SCSE102014      MANALI ANAND  08/03/2019            1
1112   16SCSE102014      MANALI ANAND  08/03/2019            1
1113   16SCSE102014      MANALI ANAND  22/03/2019            0
1114   16SCSE102014      MANALI ANAND  26/03/2019            0
1115   16SCSE102014      MANALI ANAND  22/03/2019            0
1116   16SCSE102014      MANALI ANAND  29/03/2019            1
1117   16SCSE102014      MANALI ANAND  29/03/2019            1
1118   16SCSE102014      MANALI ANAND  26/03/2019            0

[1119 rows x 4 columns]
            Date  ClassAttend
1101  15/02/2019            0
1102  15/02/2019            0
1103  12/02/2019            1
1104  12/02/2019            1
1105  12/03/2019            1
1106  02/04/2019            1
1107  12/03/2019            1
1108  02/04/2019            1
1109  15/03/2019            1
1110  15/03/2019            1
1111  08/03/2019            1
1112  08/03/2019            1
1113  22/03/2019            0
1114  26/03/2019            0
1115  22/03/2019            0
1116  29/03/2019            1
1117  29/03/2019            1
1118  26/03/2019            0

In [23]:
import pandas as pd 
  
# Creating a dict of lists 
data = {'name':["Akash", "Geeku", "Pankaj", "Sumitra", "Ramlal"], 
       'Branch':["B.Tech", "MBA", "BCA", "B.Tech", "BCA"], 
       'Score':["80", "90", "60", "30", "50"], 
       'Result': ["Pass", "Pass", "Pass", "Fail", "Fail"]} 
  
df = pd.DataFrame(data) 
  
# pivoting the dataframe 
df.pivot(index ='Result', columns ='name') 
  
df

      name  Branch Score Result
0    Akash  B.Tech    80   Pass
1    Geeku     MBA    90   Pass
2   Pankaj     BCA    60   Pass
3  Sumitra  B.Tech    30   Fail
4   Ramlal     BCA    50   Fail

### ------------------------------------------------------------------------------------------------------------------------------

## ABHAY's Program

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
#list all the files in the directory
data = pd.read_csv("/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-attendanceT/SECTION1.csv")
df = pd.DataFrame(data)

In [ ]:
cd = df.iloc [:, [5,6,7,11]]
cd.columns = ['RegistrationNo', 'StudentName', 'Date', 'Attended']
table = pd.pivot_table(cd, index = ['RegistrationNo', 'StudentName', 'Date'], aggfunc = 'sum')
print(table)

In [ ]:
table2 = table.pivot_table(index = 'RegistrationNo', columns = 'Date', values = 'Attended')
table2.fillna(0, inplace=True)
print(table2)

In [5]:
lst=[]
file = open('/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-attendanceT/testcase.txt', "r")
lst = file.read().splitlines()
L = len(lst)
T = int(lst[0])
i = 1

for j in range (0, T):
    res = ""
    reg = lst[i]
    dt = lst[i + 1]
    output = int(table2.loc[reg, dt])
    res = reg + "\n" + str(output)
    print(res)
    i += 2

                                             Attended
RegistrationNo StudentName       Date
16SCSE101002   NISHCHHAL SHARMA  02/04/2019         2
                                 08/03/2019         2
                                 12/02/2019         2
                                 12/03/2019         2
                                 15/02/2019         2
                                 15/03/2019         1
                                 22/03/2019         0
                                 26/03/2019         2
                                 29/03/2019         2
16SCSE101005   NAMAN KAPOOR      02/04/2019         2
                                 08/03/2019         2
                                 12/02/2019         0
                                 12/03/2019         2
                                 15/02/2019         2
                                 15/03/2019         0
                                 22/03/2019         0
                                 26/03/2019         2
                                 29/03/2019         2
16SCSE101012   ARNOB CHAKRABORTY 02/04/2019         2
                                 08/03/2019         2
                                 12/03/2019         2
                                 15/03/2019         2
                                 22/03/2019         0
                                 26/02/2019         2
                                 26/03/2019         2
                                 29/01/2019         0
                                 29/03/2019         2
16SCSE101015   PRAGATI KUMARI    02/04/2019         2
                                 08/03/2019         2
                                 12/02/2019         2
...                                               ...
16SCSE101798   KRISHNA AGGRAWAL  22/03/2019         0
                                 26/03/2019         2
                                 29/03/2019         2
16SCSE101889   PRASHANT SINGH    02/04/2019         0
                                 08/03/2019         0
                                 12/02/2019         0
                                 12/03/2019         0
                                 15/02/2019         0
                                 15/03/2019         0
                                 22/03/2019         0
                                 26/03/2019         0
                                 29/03/2019         0
16SCSE102013   SHIVAM DHINGRA    02/04/2019         0
                                 08/03/2019         2
                                 12/02/2019         2
                                 12/03/2019         2
                                 15/02/2019         0
                                 15/03/2019         2
                                 22/03/2019         0
                                 26/03/2019         2
                                 29/03/2019         2
16SCSE102014   MANALI ANAND      02/04/2019         2
                                 08/03/2019         2
                                 12/02/2019         2
                                 12/03/2019         2
                                 15/02/2019         0
                                 15/03/2019         2
                                 22/03/2019         0
                                 26/03/2019         0
                                 29/03/2019         2

[560 rows x 1 columns]
Date            02/04/2019  08/03/2019  12/02/2019  12/03/2019  15/02/2019  \
RegistrationNo
16SCSE101002           2.0         2.0         2.0         2.0         2.0
16SCSE101005           2.0         2.0         0.0         2.0         2.0
16SCSE101012           2.0         2.0         0.0         2.0         0.0
16SCSE101015           2.0         2.0         2.0         2.0         2.0
16SCSE101019           0.0         0.0         0.0         0.0         0.0
16SCSE101028           0.0         0.0         0.0         0.0         0.0
16SCSE101029           2.0         2.0         0.0         2.0         0.0
16SCSE101052           2.0         2.0         2.0         2.0         2.0
16SCSE101057           0.0         0.0         0.0         2.0         0.0
16SCSE101060           2.0         2.0         0.0         2.0         0.0
16SCSE101071           2.0         2.0         2.0         2.0         2.0
16SCSE101072           2.0         2.0         2.0         2.0         2.0
16SCSE101085           0.0         0.0         0.0         0.0         0.0
16SCSE101095           0.0         2.0         0.0         0.0         0.0
16SCSE101107           2.0         2.0         0.0         2.0         0.0
16SCSE101111           0.0         0.0         0.0         2.0         0.0
16SCSE101127           0.0         2.0         2.0         0.0         0.0
16SCSE101141           2.0         0.0         0.0         2.0         0.0
16SCSE101158           2.0         2.0         0.0         0.0         0.0
16SCSE101160           2.0         2.0         2.0         2.0         2.0
16SCSE101167           2.0         0.0         0.0         0.0         0.0
16SCSE101171           0.0         0.0         2.0         0.0         0.0
16SCSE101188           2.0         2.0         0.0         2.0         0.0
16SCSE101191           0.0         2.0         0.0         2.0         0.0
16SCSE101195           0.0         2.0         2.0         2.0         2.0
16SCSE101215           0.0         0.0         0.0         2.0         0.0
16SCSE101220           2.0         2.0         0.0         2.0         0.0
16SCSE101222           2.0         0.0         0.0         2.0         0.0
16SCSE101232           2.0         2.0         0.0         2.0         0.0
16SCSE101241           2.0         2.0         0.0         2.0         0.0
...                    ...         ...         ...         ...         ...
16SCSE101318           2.0         2.0         0.0         2.0         0.0
16SCSE101322           0.0         0.0         0.0         0.0         0.0
16SCSE101323           0.0         2.0         0.0         0.0         0.0
16SCSE101350           2.0         2.0         2.0         2.0         2.0
16SCSE101383           0.0         0.0         0.0         0.0         0.0
16SCSE101391           0.0         0.0         0.0         0.0         0.0
16SCSE101415           2.0         2.0         0.0         2.0         0.0
16SCSE101433           0.0         0.0         0.0         0.0         0.0
16SCSE101463           0.0         0.0         2.0         0.0         0.0
16SCSE101489           2.0         2.0         0.0         2.0         0.0
16SCSE101497           0.0         0.0         0.0         0.0         0.0
16SCSE101506           0.0         2.0         0.0         0.0         0.0
16SCSE101520           2.0         0.0         0.0         2.0         0.0
16SCSE101529           2.0         0.0         0.0         2.0         0.0
16SCSE101547           0.0         2.0         2.0         0.0         0.0
16SCSE101580           2.0         0.0         0.0         2.0         0.0
16SCSE101601           0.0         0.0         0.0         0.0         0.0
16SCSE101617           0.0         0.0         0.0         0.0         0.0
16SCSE101662           2.0         2.0         0.0         2.0         0.0
16SCSE101666           2.0         2.0         0.0         0.0         0.0
16SCSE101713           0.0         0.0         0.0         2.0         0.0
16SCSE101714           2.0         2.0         2.0         2.0         2.0
16SCSE101728           2.0         2.0         2.0         2.0         0.0
16SCSE101737           2.0         0.0         0.0         2.0         0.0
16SCSE101739           0.0         0.0         0.0         0.0         0.0
16SCSE101757           2.0         0.0         0.0         2.0         0.0
16SCSE101798           2.0         2.0         2.0         2.0         2.0
16SCSE101889           0.0         0.0         0.0         0.0         0.0
16SCSE102013           0.0         2.0         2.0         2.0         0.0
16SCSE102014           2.0         2.0         2.0         2.0         0.0

Date            15/03/2019  22/03/2019  26/02/2019  26/03/2019  29/01/2019  \
RegistrationNo
16SCSE101002           1.0         0.0         0.0         2.0         0.0
16SCSE101005           0.0         0.0         0.0         2.0         0.0
16SCSE101012           2.0         0.0         2.0         2.0         0.0
16SCSE101015           0.0         0.0         0.0         2.0         0.0
16SCSE101019           0.0         0.0         0.0         0.0         0.0
16SCSE101028           0.0         0.0         0.0         0.0         0.0
16SCSE101029           2.0         0.0         2.0         2.0         0.0
16SCSE101052           2.0         0.0         0.0         0.0         0.0
16SCSE101057           0.0         0.0         0.0         2.0         2.0
16SCSE101060           0.0         0.0         0.0         0.0         0.0
16SCSE101071           2.0         0.0         0.0         2.0         0.0
16SCSE101072           2.0         0.0         0.0         2.0         0.0
16SCSE101085           0.0         0.0         0.0         0.0         2.0
16SCSE101095           2.0         2.0         2.0         2.0         0.0
16SCSE101107           2.0         2.0         2.0         2.0         0.0
16SCSE101111           2.0         0.0         0.0         0.0         0.0
16SCSE101127           2.0         2.0         0.0         2.0         0.0
16SCSE101141           2.0         0.0         0.0         2.0         0.0
16SCSE101158           0.0         0.0         0.0         0.0         2.0
16SCSE101160           0.0         2.0         0.0         2.0         0.0
16SCSE101167           0.0         0.0         2.0         0.0         0.0
16SCSE101171           0.0         0.0         0.0         0.0         0.0
16SCSE101188           2.0         0.0         2.0         2.0         0.0
16SCSE101191           2.0         2.0         2.0         2.0         0.0
16SCSE101195           2.0         0.0         0.0         2.0         0.0
16SCSE101215           2.0         0.0         0.0         0.0         0.0
16SCSE101220           2.0         0.0         2.0         2.0         0.0
16SCSE101222           2.0         2.0         2.0         2.0         0.0
16SCSE101232           2.0         2.0         2.0         2.0         0.0
16SCSE101241           2.0         0.0         0.0         0.0         0.0
...                    ...         ...         ...         ...         ...
16SCSE101318           2.0         2.0         2.0         2.0         0.0
16SCSE101322           0.0         0.0         0.0         0.0         4.0
16SCSE101323           2.0         2.0         2.0         2.0         0.0
16SCSE101350           0.0         0.0         0.0         0.0         0.0
16SCSE101383           0.0         0.0         0.0         0.0         0.0
16SCSE101391           0.0         0.0         0.0         0.0         0.0
16SCSE101415           2.0         0.0         2.0         2.0         0.0
16SCSE101433           0.0         0.0         0.0         0.0         0.0
16SCSE101463           0.0         0.0         0.0         0.0         0.0
16SCSE101489           2.0         0.0         2.0         2.0         2.0
16SCSE101497           0.0         0.0         0.0         0.0         0.0
16SCSE101506           2.0         0.0         2.0         2.0         0.0
16SCSE101520           2.0         0.0         2.0         2.0         0.0
16SCSE101529           2.0         2.0         2.0         2.0         0.0
16SCSE101547           2.0         2.0         0.0         2.0         0.0
16SCSE101580           2.0         0.0         0.0         2.0         0.0
16SCSE101601           0.0         0.0         2.0         0.0         0.0
16SCSE101617           0.0         0.0         0.0         0.0         0.0
16SCSE101662           2.0         0.0         2.0         2.0         0.0
16SCSE101666           2.0         0.0         2.0         2.0         0.0
16SCSE101713           2.0         0.0         0.0         2.0         0.0
16SCSE101714           2.0         0.0         0.0         2.0         0.0
16SCSE101728           2.0         0.0         0.0         2.0         0.0
16SCSE101737           2.0         0.0         0.0         2.0         4.0
16SCSE101739           0.0         0.0         0.0         0.0         0.0
16SCSE101757           2.0         0.0         2.0         2.0         0.0
16SCSE101798           2.0         0.0         0.0         2.0         0.0
16SCSE101889           0.0         0.0         0.0         0.0         0.0
16SCSE102013           2.0         0.0         0.0         2.0         0.0
16SCSE102014           2.0         0.0         0.0         0.0         0.0

Date            29/03/2019
RegistrationNo
16SCSE101002           2.0
16SCSE101005           2.0
16SCSE101012           2.0
16SCSE101015           2.0
16SCSE101019           0.0
16SCSE101028           0.0
16SCSE101029           2.0
16SCSE101052           0.0
16SCSE101057           2.0
16SCSE101060           2.0
16SCSE101071           2.0
16SCSE101072           2.0
16SCSE101085           0.0
16SCSE101095           2.0
16SCSE101107           2.0
16SCSE101111           0.0
16SCSE101127           2.0
16SCSE101141           2.0
16SCSE101158           2.0
16SCSE101160           2.0
16SCSE101167           0.0
16SCSE101171           0.0
16SCSE101188           2.0
16SCSE101191           2.0
16SCSE101195           2.0
16SCSE101215           0.0
16SCSE101220           2.0
16SCSE101222           2.0
16SCSE101232           2.0
16SCSE101241           2.0
...                    ...
16SCSE101318           2.0
16SCSE101322           0.0
16SCSE101323           2.0
16SCSE101350           0.0
16SCSE101383           0.0
16SCSE101391           0.0
16SCSE101415           2.0
16SCSE101433           0.0
16SCSE101463           0.0
16SCSE101489           2.0
16SCSE101497           0.0
16SCSE101506           2.0
16SCSE101520           2.0
16SCSE101529           2.0
16SCSE101547           2.0
16SCSE101580           2.0
16SCSE101601           0.0
16SCSE101617           0.0
16SCSE101662           2.0
16SCSE101666           2.0
16SCSE101713           2.0
16SCSE101714           2.0
16SCSE101728           2.0
16SCSE101737           2.0
16SCSE101739           0.0
16SCSE101757           2.0
16SCSE101798           2.0
16SCSE101889           0.0
16SCSE102013           2.0
16SCSE102014           2.0

[64 rows x 11 columns]
16SCSE102014
2
16SCSE101350
0

## Problem 2

**Description**
- A university wants to categorize the marks scored by the students of each batch in the quizzes conducted. 

---

**Datasets**
- studentlist.csv is a csv file present at the location (/data/training/studentlist.csv) which includes the student details like enrollmentnumber, admissionno
- batchwiselist is a folder present at the location (/data/training/batchwiselist) which has multiple csv files. Each file contains the student details belonging to a batch.  For example,  1.csv  contains the student details belonging to batch1 and 2.csv contains the student details belonging to batch2 and so on.
- quiz is a folder present at the location (/data/training/quiz) which has multiple csv files.  Each file represents a quiz conducted by the university and contains all the important details. The column 'Grade/10.00' contains the marks obtained in that quiz out of maximum marks of 10.  For example quiz1.csv  contains the student details and the marks obtained by them in the first quiz. 

---

**Tasks**
Now you need to perform the following steps on this data:

 - Read the file studentlist.csv 
 - Read the files present in the folders batchwiselist,  quiz 
 - Manipulate the data and create a Statistics dataframe in such a way that it allocates marks to the students of each batch for the quizzes. 
 - Statistics dataframe for each batch should include the following column names with the respective statistics value. The column names infer the meaning of each column. 

["noofpresent", "lessthan50", "between50and60", "between60and70", "between70and80", "greaterthan80"]

 - Rows of Statistics dataframe represents the quiz. Such as, the first row under the column “between50and60” represents the number of students whose percentage is in between 50 and 60 in the first quiz. 
 - The second row under the column “between50and60” represents the number of students whose percentage is in between 50 and 60 in the second quiz. 
 - The first row under the column "noofpresent" represents the number of students who attempted the first quiz from that batch.
 - The second row under the column "noofpresent" represents the number of students who attempted the second quiz from that batch.

---

**Input Format**
You have to read a file named testcaseStudent.txt  present at the location (/data/training/testcaseStudent.txt ) which has the following lines:
 - The first line contains the number of testcase pairs.
 - Followed by a set of Batch file and Percentage range pairs. Each element of the pair is in a separate line.

**Output Format**
 - For each testcase pair n, create an output file outputn.txt  where n represents the test case pair number.
 - outputn.txt  should be present at the location (/code/outputn.txt) . This file should contain the number of students who got marks in the requested percentage range from that batch.
 - outputn.txt should consist of the values in a separate line for each quiz.

---

**Sample Test Cases**

- Sample Input
    - testcaseStudent.txt contains the following data:
        >- 2
        >- 4.csv
        >- greaterthan80
        >- 3.csv
        >- lessthan50

- Sample Output
    - output1.txt contains the following data:
        - 12
        - 45
    - output2.txt contains the following data:
        - 10
        - 15
- Explanation
    - As there are two quiz files in the quiz folder,  output file should consist of two values, each value representing a quiz.
    - In the batch 4.csv  there are 12 students who scored greater than 80 in the first quiz and 45 students in second quiz
    - In the batch 3.csv  there are 10 students who scored less than 50 in the first quiz and 15 students in second quiz

In [4]:
import pandas as pd
import numpy as np
import glob
import os

path = r'/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-new_dataset/batchwiselist'
files = os.listdir(path)
files

# #Read Studentlist CSV file
studentlistdf = pd.read_csv("/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-new_dataset/studentlist.csv")

# #Read files in folder batchwiselist
path = r'/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-new_dataset/batchwiselist'
for file in path
     df1 = pd.read_csv()

SyntaxError: invalid syntax (<ipython-input-4-1daf51fd0699>, line 15)

In [3]:
#Read files in folder batchwiselist
import pandas as pd
import numpy as np
import glob
path = r'/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-new_dataset/batchwiselist'
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    batchwiselistdf = pd.read_csv(filename, index_col=None, header=0)
    li.append(batchwiselistdf)

frame = pd.concat(li, axis=0, ignore_index=True)

batchwiselistdf

#Read files in folder quiz
path = r'/Users/pushkarravimbp/Jupyter Program Files/Edureka Assignments/2/training-new_dataset/quiz'
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    quizdf = pd.read_csv(filename, index_col=None, header=0)
    li.append(quizdf)

frame = pd.concat(li, axis=0, ignore_index=True)

quizdf

,Surname,Firstname,ID number,Institution,Department,Email address,State,Started on,Completed,Time taken,...,Q. 1 /1.00,Q. 2 /1.00,Q. 3 /1.00,Q. 4 /1.00,Q. 5 /1.00,Q. 6 /1.00,Q. 7 /1.00,Q. 8 /1.00,Q. 9 /1.00,Q. 10 /1.00
0,16BTCSES7,VEER SINGH GURJAR,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:25,06-03-2019 16:33,8 mins 8 secs,...,0,1,0,0,1,1,0,1,0,0
1,16BTCSES7,PRANSHU VERMA,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:25,06-03-2019 16:39,14 mins 41 secs,...,1,1,1,1,1,1,1,1,1,1
2,16BTCSES2,EJAZ BAKHSH,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:26,06-03-2019 16:41,15 mins 18 secs,...,0,1,0,0,1,0,1,0,0,1
3,16BTCSES7,MOHD FAIZ,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:26,06-03-2019 16:45,19 mins 2 secs,...,1,1,1,1,1,1,1,1,1,1
4,16BTCSES7,ANISH SINGH,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:28,06-03-2019 16:37,9 mins 1 sec,...,1,1,1,1,1,1,1,1,1,1
5,16BTCSES2,LAKSHMI AGRAHARI,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:28,06-03-2019 16:43,14 mins 31 secs,...,0,1,1,1,0,1,0,0,0,0
6,16BTCSES7,MOHD AHTESHAM,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:29,06-03-2019 16:31,2 mins 8 secs,...,1,1,0,1,0,0,0,0,0,0
7,16BTCSES2,KM SWETA SHARMA,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:29,06-03-2019 16:38,9 mins 31 secs,...,0,1,0,0,1,1,0,0,0,0
8,16BTCSES7,ANKIT GODELA,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:29,06-03-2019 16:35,6 mins 36 secs,...,1,1,1,1,1,1,1,1,1,1
9,16BTCSES7,SOURABH TANWAR,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:29,06-03-2019 16:32,3 mins 2 secs,...,0,0,0,0,1,1,0,0,1,1
10,16BTCSES7,RAVI RAJ SINGH,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:29,06-03-2019 16:30,1 min 19 secs,...,0,0,1,0,1,0,1,0,0,0
11,16BTCSES7,NEHA,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:29,06-03-2019 16:45,15 mins 49 secs,...,1,1,1,1,1,1,1,1,1,1
12,16BTCSES7,NISHANT KETU,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:31,06-03-2019 16:35,4 mins 22 secs,...,1,1,1,1,1,1,1,1,1,1
13,16BTCSES7,VISHAL SINGH RATHORE,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:31,06-03-2019 16:37,6 mins 17 secs,...,1,1,1,1,1,1,0,1,1,1
14,16BTCSES2,UTTAM KUMAR,NaN,NaN,NaN,NaN,In progress,06-03-2019 16:32,-,-,...,-,-,-,-,-,-,-,-,-,-
15,16BTCSES2,AAYUSH KUMAR,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:32,06-03-2019 16:38,5 mins 56 secs,...,0,1,1,1,0,0,1,0,0,1
16,16BTCSES4,SHRIKANT JHA,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:32,06-03-2019 16:42,9 mins 26 secs,...,0,1,1,1,1,1,1,1,0,0
17,16BTCSES2,Shams ahad khan,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:33,12-03-2019 16:30,5 days 23 hours,...,0,1,1,1,1,1,1,1,1,1
18,16BTCSES2,NILESH HOODA,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:33,06-03-2019 16:38,5 mins 52 secs,...,1,0,0,1,1,1,1,0,0,1
19,16BTCSES2,SHIVAM KUMAR MODANWAL,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:33,06-03-2019 16:44,11 mins 32 secs,...,0,1,0,0,1,1,1,0,1,0
20,16BTCSES2,PRITANSHU DWIVEDI,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:33,06-03-2019 16:43,9 mins 57 secs,...,1,1,1,1,1,1,1,1,1,1
21,16BTCSES4,MANISH KUMAR,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:33,13-03-2019 15:48,6 days 23 hours,...,-,-,0,-,-,-,1,-,1,-
22,16BTCSES7,UTKARSH KUMAR,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:33,06-03-2019 16:39,5 mins 57 secs,...,1,1,1,1,1,0,1,1,1,1
23,16BTCSES2,saurabh kumar,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:34,06-03-2019 16:41,7 mins 32 secs,...,1,0,1,1,1,0,0,1,1,0
24,16BTCSES2,PRANSHU,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:34,12-03-2019 15:28,5 days 22 hours,...,0,0,0,1,-,1,0,0,0,0
25,16BTCSES2,NIKHIL KUMAR SINGH,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:35,12-03-2019 16:29,5 days 23 hours,...,0,1,0,1,1,1,1,1,1,0
26,16BTCSES7,SAURABH KUMAR,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:37,06-03-2019 16:38,1 min 16 secs,...,1,1,1,1,1,1,1,1,1,1
27,16BTCSES7,HIMANSHU KUMAR,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:37,06-03-2019 16:42,4 mins 28 secs,...,1,1,1,1,1,1,1,1,1,1
28,16BTCSES1,ANSHIKA SINGH,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:38,12-03-2019 13:51,5 days 21 hours,...,-,1,-,-,1,-,-,-,1,-
29,16BTCSES7,GIRIJA KUMARI,NaN,NaN,NaN,NaN,Finished,06-03-2019 16:39,12-03-2019 15:57,5 days 23 hours,...,-,-,-,-,-,-,-,1,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651,16BTCSES5,SUSHIL KUMAR,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:37,14-03-2019 15:57,20 mins 1 sec,...,0,1,1,1,1,1,1,1,0,1
652,16BTCSDAS1,PRIYANKA,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:42,14-03-2019 15:44,1 min 28 secs,...,1,1,1,1,1,1,1,1,1,1
653,16BTCSES5,BRIJESH KUMAR SHUKLA,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:43,14-03-2019 15:57,13 mins 55 secs,...,0,1,1,1,1,1,1,1,0,0
654,16BTCSES8,Ahad,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:43,14-03-2019 15:59,15 mins 50 secs,...,1,1,1,1,1,1,1,1,1,1
655,16BTCSES5,PRASHANT VERMA,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:49,14-03-2019 16:07,18 mins 14 secs,...,1,1,1,1,1,1,1,1,1,0
656,16BTCSES5,PRAKHAR KHARE,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:49,14-03-2019 16:05,16 mins 8 secs,...,1,1,1,1,1,1,1,1,1,1
657,16BTCSES5,Aqib Jamal Siddiqui,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:49,14-03-2019 16:08,18 mins 45 secs,...,1,1,1,1,1,1,1,1,1,1
658,16BTCSES5,SURESH,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:49,14-03-2019 16:08,18 mins 30 secs,...,1,1,1,1,1,1,1,1,1,1
659,16BTCSES5,HIMANSHU SINGH,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:49,14-03-2019 16:07,17 mins 42 secs,...,1,1,1,1,1,1,1,1,1,1
660,16BTCSES5,VINOD KUMAR SINGH,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:49,14-03-2019 16:08,18 mins 33 secs,...,1,1,1,1,1,1,1,1,1,1
661,16BTCSES5,ASHISH KUMAR SINGH,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:50,14-03-2019 16:10,20 mins 2 secs,...,1,0,0,1,0,1,1,1,0,0
662,16BTCSES5,NAVNEET KUMAR,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:50,14-03-2019 16:10,20 mins 16 secs,...,1,1,1,1,1,1,1,1,1,1
663,16BTCSES5,Shobhit Rana,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:50,14-03-2019 16:08,18 mins 18 secs,...,1,1,1,1,1,1,0,1,1,1
664,16BTCSES5,RAHUL KUMAR SRIVASTAVA,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:50,14-03-2019 16:06,15 mins 35 secs,...,1,1,1,1,1,1,1,1,1,1
665,16BTCSES5,BHARAT LAL,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:50,14-03-2019 16:08,18 mins 4 secs,...,1,1,1,1,1,1,1,1,1,1
666,16BTCSES5,PRANJAL SHUKLA,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:50,14-03-2019 16:10,20 mins,...,1,1,1,1,0,1,1,1,1,0
667,16BTCSES5,SHANU KUMAR,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:50,14-03-2019 16:01,10 mins 50 secs,...,1,1,1,1,1,1,1,1,1,1
668,16BTCSES5,VAIBHAV GUPTA,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:51,14-03-2019 16:11,19 mins 37 secs,...,1,1,0,1,1,0,1,1,1,1
669,16BTCSES5,SOURAV KUMAR,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:51,14-03-2019 16:04,12 mins 32 secs,...,1,1,1,1,1,1,1,0,1,0
670,16BTCSES5,SNIGDHA,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:53,14-03-2019 16:06,13 mins 54 secs,...,1,1,1,1,1,1,1,1,1,1
671,16BTCSES5,RAJIV PRAJAPATI,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:56,14-03-2019 16:13,16 mins 53 secs,...,1,1,1,1,1,1,1,1,1,1
672,16BTCSES5,KRISHNA KANT TIWARI,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:56,14-03-2019 16:03,7 mins 22 secs,...,0,0,0,0,0,0,1,0,1,1
673,16BTCSES5,ANMOL SINGH,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:56,14-03-2019 16:06,10 mins 1 sec,...,1,1,1,1,1,1,1,1,1,1
674,16BTCSES5,SAURABH SUMAN,NaN,NaN,NaN,NaN,Finished,14-03-2019 15:56,14-03-2019 16:16,20 mins 1 sec,...,0,1,1,1,1,1,1,0,1,1
675,16BTCSES5,ANISH KUMAR,NaN,NaN,NaN,NaN,Finished,14-03-2019 16:03,14-03-2019 16:15,12 mins 28 secs,...,1,1,1,1,1,1,1,1,1,1
676,16BTCSES6,SANJEEV KUMAR PANDEY,NaN,NaN,NaN,NaN,Finished,14-03-2019 16:07,14-03-2019 16:13,6 mins 20 secs,...,1,1,1,1,1,1,1,1,1,1
677,16BTCSES6,UTKARSH GUPTA,NaN,NaN,NaN,NaN,Finished,14-03-2019 16:07,14-03-2019 16:10,3 mins 20 secs,...,1,1,1,1,1,1,1,1,1,1
678,16BTCSES6,GAURAV SAHU,NaN,NaN,NaN,NaN,Finished,14-03-2019 16:09,14-03-2019 16:11,2 mins 8 secs,...,1,1,1,1,1,1,1,1,1,1
679,16BTCSES6,MAYANK DHAWAN,NaN,NaN,NaN,NaN,Finished,14-03-2019 16:14,14-03-2019 16:20,5 mins 27 secs,...,1,1,1,1,1,1,1,1,1,1
680,Overall average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.77,0.91,0.85,0.85,0.81,0.86,0.86,0.81,0.79,0.78